# Using /home/teuben/LMT/lmtoy/data_lmt/unity/data_lmt.log
# 2018-S1-MU-78 - Science
#   script generated by source_obsnum.sh
import os
import sys

from lmtoy import runs

project="2018-S1-MU-78"

# Dictionary of sources, each with a list of obsnum's in this project
# negative obsnums are ignored in the combinations. See also comments.txt
# for obsnum specific comments and parameters!
on = {}

on["J181358.79"] = \
 [ 78160, 78161, 78162, 78164, 78165, 78166,]

on["J185537.20"] = \
 [ 78143, 78144, 78145, 78147, 78148, 78149,]

on["J234158.06"] = \
 [ 78180, 78181, 78182, 78184, 78185, 78186,]

# parameters for the first pass of the pipeline (restart=1 is automatically enforced here)
pars1 = {}

pars1["J181358.79"] = ""
pars1["J185537.20"] = ""
pars1["J234158.06"] = ""

# parameters for the (optional) second pass of the pipeline (e.g. for bank=0)
pars2 = {}

pars2["J181358.79"] = ""
pars2["J185537.20"] = ""
pars2["J234158.06"] = ""

# parameters for the (optional) third pass of the pipeline (usually for bank=1)
pars3 = {}

pars3["J181358.79"] = ""
pars3["J185537.20"] = ""
pars3["J234158.06"] = ""

# Found 3 source(s) for 2018-S1-MU-78

if __name__ == "__main__":
    runs.mk_runs(project, on, pars1, pars2, pars3, sys.argv)
